# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uhina',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/uhina',
                'lib_path': 'uhina'},
  'syms': {'uhina.core': {'uhina.core.foo': ('core.html#foo', 'uhina/core.py')}}}
